<a href="https://colab.research.google.com/github/skkrishnaa/AIMLOps_Samples/blob/main/NB_NumPy_Samples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
print(np.__version__)
print(np.show_config)
arr = np.zeros(10)
print(arr)
print(arr.shape)
arr = np.ones(20)
print(arr)
x=list(range(10,49))
x = np.arange(10,49)
print(x)
print(x[::-1])
arr=np.array([1,2,0,0,4,0])
print(np.nonzero(arr))
print([arr[i] for i in np.nonzero(arr)])
x=np.eye(3)
print(x)

1.25.2
<function show at 0x79cc5a5b4940>
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
(array([0, 1, 4]),)
[array([1, 2, 4])]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
